# Generated by Django 4.2.2 on 2023-06-15 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('texto', models.TextField()),
            ],
        ),
    ]
