# Generated by Django 4.2.2 on 2023-06-15 13:22

import csv
from django.db import migrations


def seedData(apps, schema_editor):
    """ Adiciona dados existentes ao banco de dados  """
    dataLocation = "mensagens/migrations/dados_iniciais.csv"
    Mensagem = apps.get_model("mensagens", "Mensagem")
    with open(dataLocation, newline='') as csvFile:
        initialData = csv.DictReader(csvFile)
        for row in initialData:
            message = Mensagem(
                data=row["Data"],
                status=row["Status"],
                texto=row["Mensagem"])
            message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seedData, migrations.RunPython.noop),
    ]
